### PR TITLE
Fix nested formdata

### LINKED ISSUE #1606: t.ObjectString default value does not work and t.Optional doest not work with t.ObjectString
### What version of Elysia is running?

1.4.18

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What environment are you using

1.3.4

### Are you using dynamic mode?

no

### What steps can reproduce the bug?

All this is somehow related to #1138 

First default value for ObjectString ->

```ts
it("Default value", async () => {
	const schema = t.ObjectString(
		{
			pageIndex: t.Number(),
			pageLimit: t.Number(),
		},
		{
			default: { pageIndex: 0, pageLimit: 10 },
		},
	);

	expect(Value.Create(schema)).toEqual({ pageIndex: 0, pageLimit: 10 }); // does not pass, default is '{}'
});
```

Second t.Optional with t.ObjectString ->

```ts
const schema = t.Object({
	name: t.String(),
	metadata: t.Optional(
		t.ObjectString({
			pageIndex: t.Number(),
			pageLimit: t.Number(),
		}),
	),
});

// Here all working as expected
it("Optional", async () => {
	expect(Value.Check(schema, { name: "test" })).toBe(true);
	expect(Value.Create(schema).metadata).toBeUndefined();

	expect(
		Value.Check(schema, {
			name: "test",
			metadata: { pageIndex: 1, pageLimit: 10 },
		}),
	).toBe(true);
	expect(Value.Check(schema, { name: "test", metadata: {} })).toBe(false);
});

// Here it is failing when somehow send to Elysia
it("Fail when using elysia", async () => {
	const app = new Elysia().post("/", ({ body }) => body, {
		body: schema,
	});
	const response = await app.handle(
		new Request("http://localhost/", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				name: "test",
			}),
		}),
	);
	const result = await response.json();
	console.log(result);

	expect(response.status).toBe(200); // return a 422 validation
/*
Here is the validation error ->
{
  type: "validation",
  on: "property",
  property: "/pageIndex",
  message: "Expected required property",
  summary: "Property 'pageIndex' is missing",
  found: {},
  errors: [
    {
      type: 45,
      schema: [Object ...],
      path: "/pageIndex",
      message: "Expected required property",
      errors: [],
      summary: "Property 'pageIndex' is missing",
    }, {
      type: 45,
      schema: [Object ...],
      path: "/pageLimit",
      message: "Expected required property",
      errors: [],
      summary: "Property 'pageLimit' is missing",
    }, {
      summary: "Expected number",
      type: 41,
      schema: [Object ...],
      path: "/pageIndex",
      message: "Expected number",
      errors: [],
    }, {
      summary: "Expected number",
      type: 41,
      schema: [Object ...],
      path: "/pageLimit",
      message: "Expected number",
      errors: [],
    }
  ],
}
41 | 		}),
42 | 	);
43 | 	const result = await response.json();
44 | 	console.log(result);
45 |
46 | 	expect(response.status).toBe(200);
                              ^
error: expect(received).toBe(expected)

Expected: 200
Received: 422
*/
});

// Obviously work when all options are set
it("Work when using elysia", async () => {
	const app = new Elysia().post("/", ({ body }) => body, {
		body: schema,
	});
	const response = await app.handle(
		new Request("http://localhost/", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				name: "test",
				metadata: { pageIndex: 1, pageLimit: 10 },
			}),
		}),
	);
	const result = await response.json();
	console.log(result);

	expect(response.status).toBe(200);
});
```

### What is the expected behavior?

Elysia should work when using t.ObjectString paired with t.Optional

### What do you see instead?

_No response_

### Additional information

The problem comes in the Elysia internal not the ObjectString itself. This may happen in replaceSchema internal method.
root cause -> _replaceSchemaType -> composeProperties -> _composeProperties

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

_No response_

### PR DESCRIPTION
**Pull request by Teyik0**
This fix #1606 and #1138 by adding coerceFormdata capabilities.

At first I just wanted to fix #1606 when I saw that t.Optional was'nt working with t.ObjectString but when changing t.ObjectString default value from '{}' to options.default it was breaking t.ArrayQuery. I was in a dead end.

Then after looking at the code, I understood that Elysia coercion is amazing and that I just needed that out of the box for nested formdata. Thus, I wanted to fix replaceSchema function and somehow end up rewriting it to make it more readable and functional. The root cause was somewhere in the composeProperties function, but in any case with the rewrite it's not needed anymore.

Finally, since the rewrite was working and fixing 1606, I just needed to add a coerceFormdata function such as stringToStructureCoercions for ArrayQuery. And of course a bunch of new tests (most of the PR is new test).

The only drawback is that coerceFormdata is only working for elysia type system. But all already coercion is only working for elysia type system, thus I think it's ok like this.

I hope you will take some time to review it, and, in any case I learned so much reading the code base and for that big thanks!

## Summary by CodeRabbit

* **New Features**
  * Enhanced validation for form data submissions with file uploads and complex nested structures.

* **Bug Fixes**
  * Improved handling of union-based schemas during body validation, ensuring properties are correctly extracted and processed.

* **Tests**
  * Added comprehensive test coverage for FormData handling with file uploads and nested object validation.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/schema.ts [hunk 1]
```diff
@@ -122,36 +123,63 @@ export const hasAdditionalProperties = (
 	return false
 }
 
-export const hasType = (type: string, schema: TAnySchema) => {
+/**
+ * Resolve a schema that might be a model reference (string) to the actual schema
+ */
+ export const resolveSchema = (
```
Comment (Teyik0) [inline src/schema.ts:129]: This is needed in order to resolve string imported model. Otherwise, t.model for example would not use coerceFormdata when needed.

File: src/schema.ts [hunk 2]
```diff
@@ -122,36 +123,63 @@ export const hasAdditionalProperties = (
...
+	// @ts-expect-error private property
+	if (modules && schema in modules.$defs) {
+		return (modules as TModule<{}, {}>).Import(schema as never)
+	}
+
+	// Then check models
+	return models?.[schema]
+ }
+
+export const hasType = (type: string, schema: TAnySchema): boolean => {
```
Comment (Teyik0) [inline src/schema.ts:147]: I somehow enhanced all edgecase that was previsouly not handled on this function
